apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w3y7764cx-go
  janus-idp.io/tekton: w3y7764cx-go
  backstage.io/kubernetes-id: w3y7764cx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w3y7764cx-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
